spring:
  h2.console.enabled: true
  liquibase.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    url: jdbc:h2:./testdb
#  jpa:
#    show-sql: true
logging:
  level:
    sql: info